<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Hima-PC" failures="1" tests="2" name="Default test(failed)(failed)" time="0.065" errors="0" timestamp="19 May 2020 15:16:43 GMT">
  <testcase classname="testpackage.TestNg_RetryFailDemo" name="test3" time="0.024">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at testpackage.TestNg_RetryFailDemo.test3(TestNg_RetryFailDemo.java:22)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase classname="testpackage.TestNg_RetryFailDemo" name="test2" time="0.002"/>
</testsuite> <!-- Default test(failed)(failed) -->
